apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluentd.fullname" . }}-headless
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
    app.kubernetes.io/component: aggregator
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp
      port: 24444
      targetPort: tcp
  selector:
    app.kubernetes.io/name: {{ include "fluentd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: aggregator