apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluentd.fullname" . }}-headless
  labels: {{- include "fluentd.labels" . | nindent 4 }}
    app.kubernetes.io/component: aggregator
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: tcp
    port: {{ .Values.aggregator.port }}
    targetPort: tcp
  selector: {{- include "fluentd.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: aggregator